spring:
  jpa:
    hibernate:
      ddlAuto: update
  datasource:
    url: jdbc:mysql://localhost:3306/topicdb?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: pravinroot
    driverClassName: com.mysql.cj.jdbc.Driver
